// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19Kkdd-nP2p5UA0QUz8vAfP_p4O8qKkw',
    appId: '1:436693506162:web:73657841182abdc5024aeb',
    messagingSenderId: '436693506162',
    projectId: 'photo-ai-1e1fe',
    authDomain: 'photo-ai-1e1fe.firebaseapp.com',
    storageBucket: 'photo-ai-1e1fe.firebasestorage.app',
    measurementId: 'G-VXJ49X8GBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCig4MkoI03QbOCGAQ08tyfafK637EvEM',
    appId: '1:436693506162:android:9e07b9f7df419113024aeb',
    messagingSenderId: '436693506162',
    projectId: 'photo-ai-1e1fe',
    storageBucket: 'photo-ai-1e1fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmCntG_jGc2hoSbuc9fq9_T4cdxKwL9EA',
    appId: '1:436693506162:ios:bb8b358bc275f125024aeb',
    messagingSenderId: '436693506162',
    projectId: 'photo-ai-1e1fe',
    storageBucket: 'photo-ai-1e1fe.firebasestorage.app',
    iosBundleId: 'com.example.photoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmCntG_jGc2hoSbuc9fq9_T4cdxKwL9EA',
    appId: '1:436693506162:ios:bb8b358bc275f125024aeb',
    messagingSenderId: '436693506162',
    projectId: 'photo-ai-1e1fe',
    storageBucket: 'photo-ai-1e1fe.firebasestorage.app',
    iosBundleId: 'com.example.photoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB19Kkdd-nP2p5UA0QUz8vAfP_p4O8qKkw',
    appId: '1:436693506162:web:7572b964014f1730024aeb',
    messagingSenderId: '436693506162',
    projectId: 'photo-ai-1e1fe',
    authDomain: 'photo-ai-1e1fe.firebaseapp.com',
    storageBucket: 'photo-ai-1e1fe.firebasestorage.app',
    measurementId: 'G-5BHBGES4G5',
  );
}
